"""Subclass of frmDeclToMen, which is generated by wxFormBuilder."""

from ui.CctUi import *
import re

class D2MParam:
	def __init__(self):
		self.strObject = u""
		self.bIsPtr = False
		self.strDecl = u""

# Implementing frmDeclToMen
class CCTDeclToMen( frmDeclToMen ):
	def __init__( self, parent ):
		frmDeclToMen.__init__( self, parent )

	# Virtual event handlers, overide them in your derived class
	def OnTextObject( self, event ):
		self.update_dst()

	def OnTextDecl( self, event ):
		self.update_dst()
	
	def OnCheckPtr( self, event ):
		self.update_dst()

	def update_dst(self):
		param = D2MParam()
		param.bIsPtr = self.cbtnPtr.GetValue()
		param.strDecl = self.edtDecl.GetValue()
		param.strObject = self.edtObject.GetValue()
		strDst = self.convert(param)
		self.edtMember.SetValue(strDst)

	@classmethod
	def convert(cls, param):
		pattern = re.compile('.+?\\s+([a-zA-Z_][a-zA-Z0-9_]*)')
		listRet = []
		for strValue in param.strDecl.split('\n'):
			strValue = strValue.strip()
			if strValue != '':
				ma = pattern.search(strValue)
				if ma:
					strValue = ma.group(1)
				listRet.append('%s%s%s;' % ( param.strObject, '->' if param.bIsPtr else '.' , strValue))

		return '\n'.join(listRet)
