"""Subclass of frmEnumToSwitch, which is generated by wxFormBuilder."""

from ui.CctUi import *


class E2SParam:
    def __init__(self):
        self.strSrc = u""
        self.bBreak = True
        self.strNamespace = u""
        self.strExpValue = u""


# Implementing frmEnumToSwitch
class CCTEnumToSwitch(frmEnumToSwitch):
    def __init__(self, parent):
        frmEnumToSwitch.__init__(self, parent)

    def OnTextEdtNamespace(self, event):
        self.update_dst()

    def OnCheckCbBreak(self, event):
        self.update_dst()

    def OnTextEdtEnum(self, event):
        self.update_dst()

    def OnTextEdtExpValue(self, event):
        self.update_dst()

    def update_dst(self):
        param = E2SParam()
        param.bBreak = self.cbBreak.GetValue()
        param.strNamespace = self.edtNamespace.GetValue()
        param.strSrc = self.edtEnum.GetValue()
        param.strExpValue = self.edtExpValue.GetValue()
        strDst = self.convert(param)
        self.edtSwitch.SetValue(strDst)

    @classmethod
    def convert(cls, param):
        listDes = []
        strDst = u""

        listDes.append(u"switch(%s)\n{" % param.strExpValue)
        strCase = u"case %s:" if not param.strNamespace else u"case " + param.strNamespace + u"::%s:"

        for strValue in param.strSrc.split(','):
            listDes.append(strCase % strValue.strip())
            if param.bBreak:
                listDes.append(u"break;")

        listDes.append(u"default:\nbreak;\n}")

        strDst = "\n".join(listDes)
        return strDst
