"""Subclass of frmJsonPicker, which is generated by wxFormBuilder."""

from ui.CctUi import *

import json


class JsonParam:
    def __init__(self):
        self.strJson = u""


# Implementing frmJsonPicker
class CCTJsonPicker(frmJsonPicker):
    def __init__(self, parent):
        frmJsonPicker.__init__(self, parent)

    # Handlers for frmJsonPicker events.
    def OnTextJson(self, event):
        self.update_dst()
        pass

    @classmethod
    def dict_key(cls, d, sz):
        for k, v in d.iteritems():
            sz.append(k)
            if isinstance(v, list):
                for l in v:
                    if isinstance(l, dict):
                        cls.dict_key(l, sz)
            elif isinstance(v, dict):
                cls.dict_key(v, sz)

    @classmethod
    def convert(cls, param):
        strRet = ""
        try:
            szJson = json.loads(param.strJson)
            listName = []
            cls.dict_key(szJson, listName)
            listName = set(listName)

            strRet += "enum ElemText { "
            for strName in listName:
                strRet += "ET_%s, " % strName.upper()
            if strRet[-2:] == ", ":
                strRet = strRet[:-2]
            strRet += " };\n\n"

            strRet += "const char* szElemText[] = \n{\n"
            for strName in listName:
                strRet += "\"%s\",\n" % strName
            strRet += " };\n\n"

        except:
            import traceback
            traceback.print_exc()
        finally:
            pass

        return strRet

    def update_dst(self):
        param = JsonParam()
        param.strJson = self.edtJson.GetValue()
        strDst = self.convert(param)
        self.edtRes.SetValue(strDst)
