"""Subclass of frmCppCodeTools, which is generated by wxFormBuilder."""

import wx
from ui.CctUi import *
from core.CctStringToEnum import *
from core.CctEnumToSwitch import *
from core.CctNameToClass import *
from core.CctQtClassToHeader import *
from core.CctXmlPicker import *
from core.CctJsonPicker import *
from core.CctDeclToMen import *
from res.images import *


# Implementing frmCppCodeTools
class CCTMain(frmCppCodeTools):
    def __init__(self, parent):
        frmCppCodeTools.__init__(self, parent)
        self.setup_ui()

    def __del__(self):
        pass

    def setup_ui(self):
        self.SetIcon(AppIcon.getIcon())
        self.frmSTE = CCTStringToEnum(self.lbPage)
        self.lbPage.AddPage(self.frmSTE, u"StringToEnum", True)
        self.frmETS = CCTEnumToSwitch(self.lbPage)
        self.lbPage.AddPage(self.frmETS, u"EnumToSwitch", False)
        self.frmNTC = CCTNameToClass(self.lbPage)
        self.lbPage.AddPage(self.frmNTC, u"NameToClass", False)
        self.frmQCTH = CCTQtClassToHeader(self.lbPage)
        self.lbPage.AddPage(self.frmQCTH, u"QtClassToHeader", False)
        self.frmXP = CCTXmlPicker(self.lbPage)
        self.lbPage.AddPage(self.frmXP, u"XmlPicker", False)
        self.frmJP = CCTJsonPicker(self.lbPage)
        self.lbPage.AddPage(self.frmJP, u"JsonPicker", False)
        self.frmDTM = CCTDeclToMen(self.lbPage)
        self.lbPage.AddPage(self.frmDTM, u"DeclToMen", False)

    def OnEdtHeaderMiddleUp(self, event):
        win = wx.Window.FindFocus()
        if win:
            if wx.TheClipboard.Open():
                wx.TheClipboard.SetData(wx.TextDataObject(win.GetValue()))
                wx.TheClipboard.Close()
