"""Subclass of frmQtClassToHeader, which is generated by wxFormBuilder."""

from ui.CctUi import *
import re

# Implementing frmQtClassToHeader
class CCTQtClassToHeader(frmQtClassToHeader):
    def __init__(self, parent):
        frmQtClassToHeader.__init__(self, parent)

    # Handlers for frmQtClassToHeader events.
    def OnTextClass(self, event):
        self.update_dst()

    def update_dst(self):
        strSrc = self.edtClass.GetValue()
        strDst = self.convert(strSrc)
        self.edtHeader.SetValue(strDst)

    @classmethod
    def convert(cls, strSrc):
        pattern = re.compile('\\w+')
        listRet = []
        for strValue in strSrc.split('\n'):
            strValue = strValue.strip()
            if strValue != '':
                ma = pattern.search(strValue)
                if ma:
                    strValue = ma.group(0)
                listRet.append('#include <%s>' % strValue.rstrip('*').rstrip())

        return '\n'.join(set(listRet))
