"""Subclass of frmStringToEnum, which is generated by wxFormBuilder."""

from ui.CctUi import *


class S2EParam:
    def __init__(self):
        self.strSrc = ""
        self.bWrap = False
        self.strPrefix = ""


# Implementing frmStringToEnum
class CCTStringToEnum(frmStringToEnum):
    def __init__(self, parent):
        frmStringToEnum.__init__(self, parent)

    def OnTextEdtString(self, event):
        self.update_dst()

    def OnCheckCbWrap( self, event ):
        self.update_dst()

    def OnTextEdtPrefix( self, event ):
        self.update_dst()

    @classmethod
    def convert(cls, param):
        listDes = []
        strDst = u""
        for strValue in param.strSrc.split(','):
            if strValue != "":
                listDes.append(param.strPrefix + strValue.replace('"', '').strip().upper())

        strSp = ',' if not param.bWrap else ',\n'
        strDst = strSp.join(listDes)
        return strDst

    def update_dst(self):
        param = S2EParam()
        param.strSrc = self.edtString.GetValue()
        param.bWrap = self.cbWrap.GetValue()
        param.strPrefix = self.edtPrefix.GetValue()
        strDst = self.convert(param)
        self.edtEnum.SetValue(strDst)
